routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\FooterLinksController;
use App\Http\Controllers\Admin\LoginController;
use App\Http\Controllers\Auth\UserController;
use App\Http\Controllers\NewsController;
use App\Http\Controllers\ReviewController;
use App\Http\Controllers\QuestionnairesController;


Route::group(['prefix' => 'admin'], function() {
    Route::get('login', [LoginController::class, 'showLoginForm'])->name('admin.login.page');
    Route::post('login', [LoginController::class, 'login'])->name('admin.login');
    Route::post('logout', [LoginController::class, 'logout'])->name('admin.logout');

    Route::group(['middleware' => 'auth:admin'], function() {
        Route::get('', [DashboardController::class, 'index'])->name('dashboard');
        Route::get('footer-links', [FooterLinksController::class, 'index'])->name('footer-links');

        // Users
        Route::group(['prefix' => 'users'], function() {
            Route::group(['prefix' => 'applicants'], function() {
                Route::get('/', [UserController::class, 'get_applicants'])->name('admin.applicants');
                Route::get('/edit/{id}', [UserController::class, 'edit'])->name('applicant.edit');
                Route::post('/update/{id}', [UserController::class, 'update'])->name('applicant.update');
                Route::get('/delete/{id}', [UserController::class, 'delete'])->name('applicant.delete');
            });

            Route::group(['prefix' => 'vacancy'], function() {
                Route::get('/', [UserController::class, 'get_vacancy'])->name('admin.vacancy');
                Route::get('/edit/{id}', [UserController::class, 'edit_vacancy'])->name('vacancy.edit');
                Route::post('/update/{id}', [UserController::class, 'update_vacancy'])->name('vacancy.update');
                Route::post('/delete/{id}', [UserController::class, 'delete_vacancy'])->name('vacancy.delete');
            });
            // Route::get('/', [UserController::class, 'getAllUsers'])->name('admin.users');
        });

        // News
        Route::group(['prefix' => 'news'], function() {
            Route::get('/', [NewsController::class, 'all'])->name('admin.news.all');
            Route::get('/new', [NewsController::class, 'create'])->name('admin.news.add');
            Route::get('/edit/{id}', [NewsController::class, 'edit'])->name('admin.news.edit');
            Route::post('/edit/{id}', [NewsController::class, 'update'])->name('admin.news.update');
            Route::get('/delete/{id}', [NewsController::class, 'delete'])->name('admin.news.delete');
            Route::post('/image', [NewsController::class, 'uploadImage'])->name('news.content.image.post');
        });

        // Reviews
        Route::group(['prefix' => 'reviews'], function() {
            Route::get('/', [ReviewController::class, 'all'])->name('admin.review.all');
            Route::get('/new', [ReviewController::class, 'add'])->name('admin.review.add');
            Route::post('/create', [ReviewController::class, 'create'])->name('admin.review.create');
            Route::get('/edit/{id}', [ReviewController::class, 'edit'])->name('admin.review.edit');
            Route::post('/edit/{id}', [ReviewController::class, 'update'])->name('admin.review.update');
            Route::get('/delete/{id}', [ReviewController::class, 'delete'])->name('admin.review.delete');
            Route::post('/image', [ReviewController::class, 'uploadImage'])->name('review.content.image.post');
        });
    });
});

routes/web.php
<?php

use App\Http\Controllers\Auth\ForgotPasswordController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MainController;
use App\Http\Controllers\Auth\Social\LoginController as SocialLogin;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\NewsController;
use App\Http\Controllers\VacancyController;
use App\Http\Controllers\QuestionnairesController;
use App\Http\Controllers\ImageController;
use App\Http\Controllers\Auth\UserController;
use App\Http\Controllers\WorldController;
use App\Http\Controllers\PayPalPaymentController;
use App\Http\Controllers\TariffController;

Route::get('/migrate', function () {
    Artisan::call('migrate');
    return 'DONE!';
});

Route::get('/seed', function () {
    Artisan::call('world:init');
    Artisan::call('db:seed RemoveUselessCountries');
    Artisan::call('db:seed TariffsSeeder');
    return 'DONE!';
});



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::post("/getJobType", [HomeController::class, "getJobType"]);

/** image routes */
Route::get('crop-image-upload', [ImageController::class, 'index']);
Route::post('crop-image-upload ', [ImageController::class, 'uploadCropImage']);

/** Stripe  routes **/
Route::get('stripe', 'StripePaymentController@stripe');
Route::post('stripe', 'StripePaymentController@stripePost')->name('stripe.post');


/** Paypal routes */
Route::get('paywithpaypal', array('as' => 'paywithpaypal','uses' => 'PayPalController@payWithPaypal',));
Route::post('paypal', array('as' => 'paypal','uses' => 'PayPalController@postPaymentWithpaypal',));
Route::get('paypal', array('as' => 'status','uses' => 'PayPalController@getPaymentStatus',));


Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('home', [HomeController::class, 'index'])->name('home');


/** Vacancies routes **/
Route::group(['prefix' => 'vacancies'], function () {

    Route::get('', [VacancyController::class, 'index'])->name('vacancies.list');
    Route::group(['middleware' => ['auth']], function () {
        Route::get('new', [VacancyController::class, 'create'])->name('vacancy.create');
        Route::post('store', [VacancyController::class, 'store'])->name('vacancy.store');
        Route::get('my', [VacancyController::class, 'myVacancies'])->name('vacancy.my');
        Route::get('{vacancy}/edit', [VacancyController::class, 'edit'])->name('vacancy.edit');
        Route::put('{vacancy}', [VacancyController::class, 'update'])->name('vacancy.update');
        Route::delete('{vacancy}', [VacancyController::class, 'destroy'])->name('vacancy.delete');
        Route::put('profile-update', [VacancyController::class, 'updateProfile'])->name('vacancy.profile.update');
    });

    Route::group(['middleware' => ['guest']], function () {
        Route::post('register', [VacancyController::class, 'register'])->name('vacancy.register');
    });

    Route::get('{vacancy}', [VacancyController::class, 'show'])->name('vacancy.show');
});


/** News routes **/
Route::group(['prefix' => 'news'], function () {
    Route::get('', [NewsController::class, 'index'])->name('news.list');
    Route::get('{id}', [NewsController::class, 'show'])->name('news.single');
});


/** Questionnaires routes **/
Route::group(['prefix' => 'questionnaires'], function () {
    Route::get('', [QuestionnairesController::class, 'index'])->name('questionnaires.list');

    Route::group(['middleware' => ['auth']], function () {
        Route::get('new', [QuestionnairesController::class, 'create'])->name('questionnaires.create');
        Route::post('store', [QuestionnairesController::class, 'store'])->name('questionnaires.store');
        Route::get('edit/{id}', [QuestionnairesController::class, 'myQuestionnaires'])->name('questionnaires.edit');

        Route::put('profile', [QuestionnairesController::class, 'updateProfile'])->name('questionnaire.profile.update');
        Route::put('profile/edit', [QuestionnairesController::class, 'editProfile'])->name('questionnaire.profile.edit');
    });

    Route::group(['middleware' => ['guest']], function () {
        Route::post('register', [QuestionnairesController::class, 'register'])->name('applicant.register');
    });

    Route::get('{id}', [QuestionnairesController::class, 'show'])->name('questionnaires.show');
});


/** Favorites routes **/
Route::group(['prefix' => 'favorites', 'middleware' => ['auth']], function () {

    Route::post('', [QuestionnairesController::class, 'addFavorite'])->name('favorite.add');
});


Route::group(['middleware' => ['auth']], function () {
    Route::group(['prefix' => 'profile'], function () {
        Route::get('', [UserController::class, 'profilePage'])->name('profile');
        Route::delete('', [UserController::class, 'delete'])->name('profile.delete');

        Route::delete('image/{id}', [UserController::class, 'deleteImage'])->name('profile.delete.image');

        Route::get('payments', [UserController::class, 'payments'])->name('profile.payments');
        Route::post('subscribe', [UserController::class, 'subscribe'])->name('profile.subscribe');
    });
});

Route::get('world-countries', [WorldController::class, 'getCountriesSelect']);
Route::get('world-regions', [WorldController::class, 'getRegionsSelect']);
Route::get('world-cities', [WorldController::class, 'getCitiesSelect']);

Route::get('english', [MainController::class, 'english'])->name('english');
Route::get('about', [MainController::class, 'about'])->name('about.list');
Route::get('contacts', [MainController::class, 'contacts'])->name('contacts.list');
Route::get('how-it-work', [MainController::class, 'howItWork'])->name('howItWork.list');



Route::get('tariffs', [TariffController::class, 'tariffs'])
//    ->middleware('auth')
    ->name('tariffs');

Route::get('check_in_', [MainController::class, 'check_in_']);

Route::group(['middleware' => ['guest']], function (){
    Route::group(['prefix' => 'auth'], function () {
        Route::get('{driver}', [SocialLogin::class, 'redirectToProvider'])->name('social.auth');
        Route::get('{driver}/callback', [SocialLogin::class, 'handleProviderCallback'])->name('social.callback');
    });
});

Route::get('forget-password', [ForgotPasswordController::class, 'showForgetPasswordForm'])->name('forget.password.get');
Route::post('forget-password', [ForgotPasswordController::class, 'submitForgetPasswordForm'])->name('forget.password.post');
Route::get('reset-password/{token}', [ForgotPasswordController::class, 'showResetPasswordForm'])->name('reset.password.get');
Route::post('reset-password', [ForgotPasswordController::class, 'submitResetPasswordForm'])->name('reset.password.post');



/** Paypal routes by Ara Mnatsyan **/
Route::get('handle-payment', [PayPalPaymentController::class, 'handlePayment'])->name('make.payment');
Route::get('cancel-payment', [PayPalPaymentController::class, 'paymentCancel'])->name('cancel.payment');
Route::get('payment-success', [PayPalPaymentController::class, 'paymentSuccess'])->name('success.payment');

app/Models/Vacancy.php
<?php

namespace App\Models;


use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Support\Carbon;

class Vacancy extends Model
{
    use HasFactory;

    protected $table = 'vacancies';

    protected $fillable = [
        'title',
        'user_id',
//        'position_id',
//        'document_id',
        'driver_license',
        'salary',
        'price_period_id',
        'recommendations',
        'comments',
        'country_id',
        'region_id',
        'city_id',
        'published',
        'is_paid',
        'is_top',
    ];

    public function scopeWithAll($query)
    {
        $query->with('author', 'pricePeriod', 'country', 'city', 'documents', 'positions', 'accommodations', 'languages', 'responds');
    }

    const DEFAULT_IMAGE = 'img/profile.jpg';

    public function getAvatarAttribute(): string
    {
        return $this->images->count() > 0
            ? $this->images->first()->path
            : self::DEFAULT_IMAGE;
    }


    public function getFillableFields()
    {
        return $this->fillable;
    }

    public function author()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function getFromDateAttribute()
    {
       return Carbon::parse($this->updated_at)->format('d-m-Y');
    }

    public function getDateCommentAttribute()
    {
        return Carbon::parse($this->crated_at)->format('d-m-Y');
    }

    public function pricePeriod()
    {
        return $this->hasOne(PricePeriod::class, 'id', "price_period_id");
    }


    public function country()
    {
        return $this->hasOne(Country::class,'id', 'country_id');
    }

    public function getCountryNameAttribute()
    {
        return $this->country ? $this->country->name : 'Все страны';
    }

    public function city()
    {
        return $this->hasOne(City::class,'id', 'city_id');
    }

    public function getCityNameAttribute()
    {
        return $this->city ? $this->city->name : '';
    }

    public function region()
    {
        return $this->hasOne(Region::class,'id', 'region_id');
    }

    public function getRegionNameAttribute()
    {
        return $this->region ? $this->region->name : 'Района Нет';
    }

    /**
     * @return BelongsToMany
     */
    public function documents(): BelongsToMany
    {
        return $this->belongsToMany(
            Document::class,
            'vacancy_documents',
            'vacancy_id',
            'document_id'
        );
    }

    /**
     * @return BelongsToMany
     */
    public function positions(): BelongsToMany
    {
        return $this->belongsToMany(
            Position::class,
            'vacancy_positions',
            'vacancy_id',
            'position_id',
        );
    }

    /**
     * @return BelongsToMany
     */
    public function accommodations() : BelongsToMany
    {
        return $this->belongsToMany(
            Accommodation::class,
            'vacancy_accommodations',
            'vacancy_id',
            'accommodation_id'
        );
    }

    /**
     * @return string
     */
    public function getAccommodationNamesAttribute(): string
    {
        return count($this->accommodations) ? implode(',', $this->accommodations()->pluck('name')->toArray()) : '';
    }


    public function getDocumentNameAttribute()
    {
        return count($this->documents) ? implode(',', $this->documents()->pluck('name')->toArray()) : ' ';

    }

    public function getPositionNameAttribute()
    {
        return count($this->positions) ? implode(',', $this->positions()->pluck('name')->toArray()) : ' ';

    }
    /**
     * @return BelongsToMany
     */
    public function languages() : BelongsToMany
    {
        return $this->belongsToMany(
            Language::class,
            'vacancy_required_languages',
            'vacancy_id',
            'language_id'
        );
    }

    public function getLanguageNameAttribute()
    {
        return count($this->languages) ? implode(',', $this->languages()->pluck('name')->toArray()) : ' ';

    }

    /**
     * @return BelongsToMany
     */
    public function responds() : BelongsToMany
    {
        return $this->belongsToMany(
            User::class,
            'vacancy_responds',
            'vacancy_id',
            'user_id'
        )->withPivot('note');
    }


}

resources/views/inc/flash-messages.blade.php
@foreach(['success', 'danger', 'info', 'warning'] as $message)
    @if(session()->has($message))
        <div class="alert alert-{{$message}}">
            {{ session()->get($message) }}
        </div>
    @endif
@endforeach

resources/views/inc/footer-jobs-links.blade.php
<div class="footer__item mob_none ">
    <ul class="footer__list footer__list_just">
    <li>
        <ul>

            @foreach($job_type as $id => $jobs)
                <li><a href="{{ route('vacancies.list', ['position' => [$jobs->id_positions]]) }}">{{ $jobs->name }}</a></li>
            @endforeach

            <li><a href="{{ route('vacancies.list', ['accommodation' => [43075]]) }}">Работа с проживанием</a></li>
        </ul>
    </li>
</ul>
</div>
@foreach(array_chunk($applicant_place,8) as $links)
    <div class="footer__item mob_none">
        <ul class="footer__list">
            @foreach($links as $id => $link)
                <li><a href="{{ route('questionnaires.list', ['city' => [$link['city_id']]]) }}">{{ $link['name'] }}</a></li>
            @endforeach
        </ul>
    </div>
@endforeach

<div class="footer__item footer__item_mob">
    <div class="footer__info">
        <a href="#" class="link-icon">
                        <span class="link-icon__icon">
                            <i class="svg-icon svg-icon_info svg-icon_col">
                                <svg>
                                    <use xlink:href="{{asset('img/svg/sprite.svg#info')}}"></use>
                                </svg>
                            </i>
                            <span>?</span>
                        </span>
            <span class="link-icon__text">Задать вопрос</span>
        </a>
    </div>
    <ul class="footer__list">
        <li><a href="{{ route('about.list') }}">About | О проекте</a></li>
        <li><a href="{{route('news.list')}}">News | Новости</a></li>
        <li><a href="{{ route('contacts.list') }}">Contacts | Контакты</a></li>
        <li><a href="{{ route('howItWork.list') }}">How it works</a></li>
    </ul>
    <div class="language">
        <img src="{{asset('img/lang__ru.png')}}" alt="ru" data-google-lang="ru" class="language__img">
        <img src="{{asset('img/lang__en.png')}}" alt="en" data-google-lang="en" class="language__img">
        <img src="{{asset('img/lang__de.png')}}" alt="de" data-google-lang="de" class="language__img">
        <img src="{{asset('img/lang__fr.png')}}" alt="fr" data-google-lang="fr" class="language__img">
        <img src="{{asset('img/lang__pt.png')}}" alt="pt" data-google-lang="pt" class="language__img">
    </div>

</div>

resources/views/inc/footer.blade.php
<div class="footer">
    <div class="container">
        <div class="footer-top-mob js-footer-top-mob"></div>
        <div class="footer__row row_flex footer__row_top job_link">






        </div>
        <div class="footer__row row_flex footer-bottom js-footer-bottom">
            <div class="footer-bottom__item footer-bottom__item_mob row_flex js-wr-logo">
                <div class="footer__logo js-footer-logo">
                    <a href="/">
                        <img src="{{asset('img/svg/logo-site.svg')}}" alt="logo-footer">
                    </a>
                </div>
                <div class="footer__year">
                    <span>© 2012 — 2020</span>
                </div>
            </div>
            <div class="footer-bottom__item js-wr-social footer-bottom__item_mob">
                <div class="social js-footer-social">
                    <ul class="social__list">
                        <li class="social__item">
                            <a href="https://www.facebook.com/rusnyanya" class="social__link social__link_fb">
                                <svg class="svg-icon">
                                    <use xlink:href="{{asset('img/svg/sprite.svg#fb')}}"></use>
                                </svg>
                            </a>
                        </li>
                        <li class="social__item">
                            <a href="https://web.telegram.org" class="social__link social__link_tl">
                                <svg class="svg-icon">
                                    <use xlink:href="{{asset('img/svg/sprite.svg#tl')}}"></use>
                                </svg>
                            </a>
                        </li>
                        <li class="social__item">
                            <a href="https://vk.com/club44511022" class="social__link social__link_vk">
                                <svg class="svg-icon">
                                    <use xlink:href="{{asset('img/svg/sprite.svg#vk')}}"></use>
                                </svg>
                            </a>
                        </li>
                        <li class="social__item">
                            <a href="https://www.youtube.com/channel/UCw5HUCcvNKr_XVt8XkNTHSw" class="social__link social__link_yo">
                                <svg class="svg-icon">
                                    <use xlink:href="{{asset('img/svg/sprite.svg#yo')}}"></use>
                                </svg>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="footer-bottom__item">
                <div class="payment">
                    <a href="{{asset("paywithpaypal")}}">
                        <div class="payment__item">
                                <img src="{{asset('img/img-pay.png')}}" alt="img">
                        </div>
                    </a>
                    <div class="payment__item">
                        <img src="{{asset('img/visa.png')}}" alt="img">
                    </div>
                    <div class="payment__item pay-card">
                        <img src="{{asset('img/mastercart.png')}}" alt="img">
                    </div>
                    <div class="payment__item pay-card">
                        <img src="{{asset('img/multipro.png')}}" alt="img">
                    </div>
                </div>
            </div>
            <div class="footer-bottom__item footer-bottom__item_developer">
                <div class="developer">
                    Разработка —  <a href="https://webstart.am">Webstart</a><br>
                    Дизайн —<a href="https://alexey-popov.com/"> Алексей Попов</a>

                </div>
            </div>
        </div>
    </div>

</div>

resources/views/inc/header.blade.php
<header class="header">
    <div class="container">
        <div class="header__row js-header-row row_flex">
            <div class="header__logo">
                <!-- на внутренних страницах убираем класс no-pointer-->
                <a href="/" class="">
                    <img src="{{asset('img/svg/logo-site.svg')}}" alt="logo-site">
                </a>
            </div>
            <div class="header__item item-header-menu js-menu">
                <nav class="header__menu menu-header">
                    <ul class="menu-header__list">
                        <li class="menu-header__item">
                            <!-- для активного пункта добавить класс header__link_active -->
                            <a href="{{ route('questionnaires.list') }}" class="header__link {{ url()->current() == route('questionnaires.list') ? 'header__link_active' : '' }}"
                            >Анкеты</a>
                        </li>
                        <li class="menu-header__item">
                            <a href="{{ route('vacancies.list') }}" class="header__link {{ url()->current() == route('vacancies.list') ? 'header__link_active' : '' }}"
                            >Вакансии</a>
                        </li>
                        <li class="menu-header__item">
                            <a href="{{ route('english') }}" class="header__link {{ url()->current() == route('english') ? 'header__link_active' : '' }}"
                            >English</a>
                        </li>
                    </ul>
                </nav>
            </div>
            <div class="header__item item-header-rating js-mob-rating">
                <div class="rating">
                    <ul class="rating__list">
                        <li class="rating__item rating__item_active">
                            <i class="svg-icon">
                                <svg>
                                    <use xlink:href="img/svg/sprite.svg#star"></use>
                                </svg>
                            </i>
                        </li>
                        <li class="rating__item rating__item_active">
                            <i class="svg-icon">
                                <svg>
                                    <use xlink:href="img/svg/sprite.svg#star"></use>
                                </svg>
                            </i>
                        </li>
                        <li class="rating__item rating__item_active">
                            <i class="svg-icon">
                                <svg>
                                    <use xlink:href="img/svg/sprite.svg#star"></use>
                                </svg>
                            </i>
                        </li>
                        <li class="rating__item rating__item_active">
                            <i class="svg-icon">
                                <svg>
                                    <use xlink:href="img/svg/sprite.svg#star"></use>
                                </svg>
                            </i>
                        </li>
                        <li class="rating__item">
                            <i class="svg-icon">
                                <svg>
                                    <use xlink:href="img/svg/sprite.svg#star"></use>
                                </svg>
                            </i>
                        </li>
                    </ul>
                    <a href="#" class="rating__text">
                        <span>8.5</span> facebook rating
                    </a>
                </div>
            </div>


            @guest
                <div class="header__item item-header-login-registration js-mob-login-registration">
                    <a  class="header__login-registration js-btn-popup header__link">
                        <i class="svg-icon">
                            <svg>
                                <use xlink:href="img/svg/sprite.svg#key"></use>
                            </svg>
                        </i>
                        <span id="login">Вход и регистрация </span>
                    </a>
                </div>
            @else
                <div class="header__item header__item-user header-user js-header-user">
                    <div class="header-user__wr">
                        <div class="header-user__row">
                            <div class="header-user__img">
                                <a href="#">
                                    <img src="{{ asset(auth()->user()->avatar) }}" alt="img">
                                </a>
                            </div>
                            <div class="header-user__name">
                                <a href="#">
                                    <span>{{ auth()->user()->name }}</span>
                                    <i class="svg-icon">
                                        <svg>
                                            <use xlink:href="img/"></use>
                                        </svg>
                                    </i>
                                </a>
                            </div>
                        </div>
                        <div class="header-user__menu-wr">
                            <div class="header-user__menu">
                                <ul>
                                    <li><a href="{{ route('profile') }}" id="profile-btn">Профиль</a></li>
                                    <form action="{{ route('logout') }}" method="POST" id="logoutForm">
                                        @csrf
                                        <li><a href="javascript:void(0);" class="aside-menu__link" id="logout-btn">Выход</a></li>
{{--                                        <li><a href="javascript:void(0);" id="logout-btn">Выход</a></li>--}}
                                    </form>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
        @endauth


            <!-- burger-menu_active -->
            <div class="burger-menu js-burger-menu">
                <span></span>
            </div>
        </div>
    </div>

    <!-- mob-menu_open -->
    <div class="mob-menu js-mob-menu"></div>
</header>