routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\FooterLinksController;
use App\Http\Controllers\Admin\LoginController;
use App\Http\Controllers\Auth\UserController;
use App\Http\Controllers\NewsController;
use App\Http\Controllers\ReviewController;
use App\Http\Controllers\QuestionnairesController;


Route::group(['prefix' => 'admin'], function() {
    Route::get('login', [LoginController::class, 'showLoginForm'])->name('admin.login.page');
    Route::post('login', [LoginController::class, 'login'])->name('admin.login');
    Route::post('logout', [LoginController::class, 'logout'])->name('admin.logout');

    Route::group(['middleware' => 'auth:admin'], function() {
        Route::get('', [DashboardController::class, 'index'])->name('dashboard');
        Route::get('footer-links', [FooterLinksController::class, 'index'])->name('footer-links');

        // Users
        Route::group(['prefix' => 'users'], function() {
            Route::group(['prefix' => 'applicants'], function() {
                Route::get('/', [UserController::class, 'get_applicants'])->name('admin.applicants');
                Route::get('/edit/{id}', [UserController::class, 'edit'])->name('applicant.edit');
                Route::post('/update/{id}', [UserController::class, 'update'])->name('applicant.update');
                Route::get('/delete/{id}', [UserController::class, 'delete'])->name('applicant.delete');
            });

            Route::group(['prefix' => 'vacancy'], function() {
                Route::get('/', [UserController::class, 'get_vacancy'])->name('admin.vacancy');
                Route::get('/edit/{id}', [UserController::class, 'edit_vacancy'])->name('vacancy.edit');
                Route::post('/update/{id}', [UserController::class, 'update_vacancy'])->name('vacancy.update');
                Route::post('/delete/{id}', [UserController::class, 'delete_vacancy'])->name('vacancy.delete');
            });
            // Route::get('/', [UserController::class, 'getAllUsers'])->name('admin.users');
        });

        // News
        Route::group(['prefix' => 'news'], function() {
            Route::get('/', [NewsController::class, 'all'])->name('admin.news.all');
            Route::get('/new', [NewsController::class, 'create'])->name('admin.news.add');
            Route::get('/edit/{id}', [NewsController::class, 'edit'])->name('admin.news.edit');
            Route::post('/edit/{id}', [NewsController::class, 'update'])->name('admin.news.update');
            Route::get('/delete/{id}', [NewsController::class, 'delete'])->name('admin.news.delete');
            Route::post('/image', [NewsController::class, 'uploadImage'])->name('news.content.image.post');
        });

        // Reviews
        Route::group(['prefix' => 'reviews'], function() {
            Route::get('/', [ReviewController::class, 'all'])->name('admin.review.all');
            Route::get('/new', [ReviewController::class, 'add'])->name('admin.review.add');
            Route::post('/create', [ReviewController::class, 'create'])->name('admin.review.create');
            Route::get('/edit/{id}', [ReviewController::class, 'edit'])->name('admin.review.edit');
            Route::post('/edit/{id}', [ReviewController::class, 'update'])->name('admin.review.update');
            Route::get('/delete/{id}', [ReviewController::class, 'delete'])->name('admin.review.delete');
            Route::post('/image', [ReviewController::class, 'uploadImage'])->name('review.content.image.post');
        });
    });
});

routes/web.php
<?php

use App\Http\Controllers\Auth\ForgotPasswordController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MainController;
use App\Http\Controllers\Auth\Social\LoginController as SocialLogin;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\NewsController;
use App\Http\Controllers\VacancyController;
use App\Http\Controllers\QuestionnairesController;
use App\Http\Controllers\ImageController;
use App\Http\Controllers\Auth\UserController;
use App\Http\Controllers\WorldController;
use App\Http\Controllers\PayPalPaymentController;
use App\Http\Controllers\TariffController;

Route::get('/migrate', function () {
    Artisan::call('migrate');
    return 'DONE!';
});

Route::get('/seed', function () {
    Artisan::call('world:init');
    Artisan::call('db:seed RemoveUselessCountries');
    Artisan::call('db:seed TariffsSeeder');
    return 'DONE!';
});



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::post("/getJobType", [HomeController::class, "getJobType"]);

/** image routes */
Route::get('crop-image-upload', [ImageController::class, 'index']);
Route::post('crop-image-upload ', [ImageController::class, 'uploadCropImage']);

/** Stripe  routes **/
Route::get('stripe', 'StripePaymentController@stripe');
Route::post('stripe', 'StripePaymentController@stripePost')->name('stripe.post');


/** Paypal routes */
Route::get('paywithpaypal', array('as' => 'paywithpaypal','uses' => 'PayPalController@payWithPaypal',));
Route::post('paypal', array('as' => 'paypal','uses' => 'PayPalController@postPaymentWithpaypal',));
Route::get('paypal', array('as' => 'status','uses' => 'PayPalController@getPaymentStatus',));


Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('home', [HomeController::class, 'index'])->name('home');


/** Vacancies routes **/
Route::group(['prefix' => 'vacancies'], function () {

    Route::get('', [VacancyController::class, 'index'])->name('vacancies.list');
    Route::group(['middleware' => ['auth']], function () {
        Route::get('new', [VacancyController::class, 'create'])->name('vacancy.create');
        Route::post('store', [VacancyController::class, 'store'])->name('vacancy.store');
        Route::get('my', [VacancyController::class, 'myVacancies'])->name('vacancy.my');
        Route::get('{vacancy}/edit', [VacancyController::class, 'edit'])->name('vacancy.edit');
        Route::put('{vacancy}', [VacancyController::class, 'update'])->name('vacancy.update');
        Route::delete('{vacancy}', [VacancyController::class, 'destroy'])->name('vacancy.delete');
        Route::put('profile-update', [VacancyController::class, 'updateProfile'])->name('vacancy.profile.update');
    });

    Route::group(['middleware' => ['guest']], function () {
        Route::post('register', [VacancyController::class, 'register'])->name('vacancy.register');
    });

    Route::get('{vacancy}', [VacancyController::class, 'show'])->name('vacancy.show');
});


/** News routes **/
Route::group(['prefix' => 'news'], function () {
    Route::get('', [NewsController::class, 'index'])->name('news.list');
    Route::get('{id}', [NewsController::class, 'show'])->name('news.single');
});


/** Questionnaires routes **/
Route::group(['prefix' => 'questionnaires'], function () {
    Route::get('', [QuestionnairesController::class, 'index'])->name('questionnaires.list');

    Route::group(['middleware' => ['auth']], function () {
        Route::get('new', [QuestionnairesController::class, 'create'])->name('questionnaires.create');
        Route::post('store', [QuestionnairesController::class, 'store'])->name('questionnaires.store');
        Route::get('edit/{id}', [QuestionnairesController::class, 'myQuestionnaires'])->name('questionnaires.edit');

        Route::put('profile', [QuestionnairesController::class, 'updateProfile'])->name('questionnaire.profile.update');
        Route::put('profile/edit', [QuestionnairesController::class, 'editProfile'])->name('questionnaire.profile.edit');
    });

    Route::group(['middleware' => ['guest']], function () {
        Route::post('register', [QuestionnairesController::class, 'register'])->name('applicant.register');
    });

    Route::get('{id}', [QuestionnairesController::class, 'show'])->name('questionnaires.show');
});


/** Favorites routes **/
Route::group(['prefix' => 'favorites', 'middleware' => ['auth']], function () {

    Route::post('', [QuestionnairesController::class, 'addFavorite'])->name('favorite.add');
});


Route::group(['middleware' => ['auth']], function () {
    Route::group(['prefix' => 'profile'], function () {
        Route::get('', [UserController::class, 'profilePage'])->name('profile');
        Route::delete('', [UserController::class, 'delete'])->name('profile.delete');

        Route::delete('image/{id}', [UserController::class, 'deleteImage'])->name('profile.delete.image');

        Route::get('payments', [UserController::class, 'payments'])->name('profile.payments');
        Route::post('subscribe', [UserController::class, 'subscribe'])->name('profile.subscribe');
    });
});

Route::get('world-countries', [WorldController::class, 'getCountriesSelect']);
Route::get('world-regions', [WorldController::class, 'getRegionsSelect']);
Route::get('world-cities', [WorldController::class, 'getCitiesSelect']);

Route::get('english', [MainController::class, 'english'])->name('english');
Route::get('about', [MainController::class, 'about'])->name('about.list');
Route::get('contacts', [MainController::class, 'contacts'])->name('contacts.list');
Route::get('how-it-work', [MainController::class, 'howItWork'])->name('howItWork.list');



Route::get('tariffs', [TariffController::class, 'tariffs'])
//    ->middleware('auth')
    ->name('tariffs');

Route::get('check_in_', [MainController::class, 'check_in_']);

Route::group(['middleware' => ['guest']], function (){
    Route::group(['prefix' => 'auth'], function () {
        Route::get('{driver}', [SocialLogin::class, 'redirectToProvider'])->name('social.auth');
        Route::get('{driver}/callback', [SocialLogin::class, 'handleProviderCallback'])->name('social.callback');
    });
});

Route::get('forget-password', [ForgotPasswordController::class, 'showForgetPasswordForm'])->name('forget.password.get');
Route::post('forget-password', [ForgotPasswordController::class, 'submitForgetPasswordForm'])->name('forget.password.post');
Route::get('reset-password/{token}', [ForgotPasswordController::class, 'showResetPasswordForm'])->name('reset.password.get');
Route::post('reset-password', [ForgotPasswordController::class, 'submitResetPasswordForm'])->name('reset.password.post');



/** Paypal routes by Ara Mnatsyan **/
Route::get('handle-payment', [PayPalPaymentController::class, 'handlePayment'])->name('make.payment');
Route::get('cancel-payment', [PayPalPaymentController::class, 'paymentCancel'])->name('cancel.payment');
Route::get('payment-success', [PayPalPaymentController::class, 'paymentSuccess'])->name('success.payment');

app/Models/Vacancy.php
<?php

namespace App\Models;


use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Support\Carbon;

class Vacancy extends Model
{
    use HasFactory;

    protected $table = 'vacancies';

    protected $fillable = [
        'title',
        'user_id',
//        'position_id',
//        'document_id',
        'driver_license',
        'salary',
        'price_period_id',
        'recommendations',
        'comments',
        'country_id',
        'region_id',
        'city_id',
        'published',
        'is_paid',
        'is_top',
    ];

    public function scopeWithAll($query)
    {
        $query->with('author', 'pricePeriod', 'country', 'city', 'documents', 'positions', 'accommodations', 'languages', 'responds');
    }

    const DEFAULT_IMAGE = 'img/profile.jpg';

    public function getAvatarAttribute(): string
    {
        return $this->images->count() > 0
            ? $this->images->first()->path
            : self::DEFAULT_IMAGE;
    }


    public function getFillableFields()
    {
        return $this->fillable;
    }

    public function author()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function getFromDateAttribute()
    {
       return Carbon::parse($this->updated_at)->format('d-m-Y');
    }

    public function getDateCommentAttribute()
    {
        return Carbon::parse($this->crated_at)->format('d-m-Y');
    }

    public function pricePeriod()
    {
        return $this->hasOne(PricePeriod::class, 'id', "price_period_id");
    }


    public function country()
    {
        return $this->hasOne(Country::class,'id', 'country_id');
    }

    public function getCountryNameAttribute()
    {
        return $this->country ? $this->country->name : 'Все страны';
    }

    public function city()
    {
        return $this->hasOne(City::class,'id', 'city_id');
    }

    public function getCityNameAttribute()
    {
        return $this->city ? $this->city->name : '';
    }

    public function region()
    {
        return $this->hasOne(Region::class,'id', 'region_id');
    }

    public function getRegionNameAttribute()
    {
        return $this->region ? $this->region->name : 'Района Нет';
    }

    /**
     * @return BelongsToMany
     */
    public function documents(): BelongsToMany
    {
        return $this->belongsToMany(
            Document::class,
            'vacancy_documents',
            'vacancy_id',
            'document_id'
        );
    }

    /**
     * @return BelongsToMany
     */
    public function positions(): BelongsToMany
    {
        return $this->belongsToMany(
            Position::class,
            'vacancy_positions',
            'vacancy_id',
            'position_id',
        );
    }

    /**
     * @return BelongsToMany
     */
    public function accommodations() : BelongsToMany
    {
        return $this->belongsToMany(
            Accommodation::class,
            'vacancy_accommodations',
            'vacancy_id',
            'accommodation_id'
        );
    }

    /**
     * @return string
     */
    public function getAccommodationNamesAttribute(): string
    {
        return count($this->accommodations) ? implode(',', $this->accommodations()->pluck('name')->toArray()) : '';
    }


    public function getDocumentNameAttribute()
    {
        return count($this->documents) ? implode(',', $this->documents()->pluck('name')->toArray()) : ' ';

    }

    public function getPositionNameAttribute()
    {
        return count($this->positions) ? implode(',', $this->positions()->pluck('name')->toArray()) : ' ';

    }
    /**
     * @return BelongsToMany
     */
    public function languages() : BelongsToMany
    {
        return $this->belongsToMany(
            Language::class,
            'vacancy_required_languages',
            'vacancy_id',
            'language_id'
        );
    }

    public function getLanguageNameAttribute()
    {
        return count($this->languages) ? implode(',', $this->languages()->pluck('name')->toArray()) : ' ';

    }

    /**
     * @return BelongsToMany
     */
    public function responds() : BelongsToMany
    {
        return $this->belongsToMany(
            User::class,
            'vacancy_responds',
            'vacancy_id',
            'user_id'
        )->withPivot('note');
    }


}

resources/views/vacancies/aside.blade.php
<div class="section-con__aside">
    <div class="aside-menu">
        <ul class="aside-menu__list">
            <li class="aside-menu__item">
                <a href="{{ route('vacancy.my') }}" class="aside-menu__link {{ url()->current() == route('vacancy.my') ? 'aside-menu__link_active' : '' }}"
                >Мои Вакансии</a>
            </li>
            <li class="aside-menu__item">
                <a href="{{ route('vacancy.create') }}" class="aside-menu__link {{ url()->current() == route('vacancy.create') ? 'aside-menu__link_active' : '' }}"
                >Добавить вакансию</a>
            </li>
            <li class="aside-menu__item">
                <a href="{{ route('profile') }}" class="aside-menu__link {{ url()->current() == route('profile') ? 'aside-menu__link_active' : '' }}"
                >Редактирование</a>
            </li>
            <li class="aside-menu__item">
                <a href="{{ route('profile.payments') }}" class="aside-menu__link {{ url()->current() == route('profile.payments') ? 'aside-menu__link_active' : '' }}"
                >Оплата аккаунта</a>
            </li>
{{--            <li class="aside-menu__item">--}}
{{--                <a href="{{ route('profile.tariffs') }}" class="aside-menu__link {{ url()->current() == route('profile.tariffs') ? 'aside-menu__link_active' : '' }}"--}}
{{--                >Тарифы</a>--}}
{{--            </li>--}}
{{--            <li class="aside-menu__item">--}}
{{--                @if(auth()->user()->subscriptions_enabled)--}}
{{--                    <a href="javascript:void(0);" class="aside-menu__link" id="subscribe-btn" data-value="0">Отписаться от рассылки</a>--}}
{{--                @else--}}
{{--                    <a href="javascript:void(0);" class="aside-menu__link" id="subscribe-btn" data-value="1">Подписаться на рассылку</a>--}}
{{--                @endif--}}
{{--            </li>--}}
            <li class="aside-menu__item">
                <form action="{{ route('profile.delete') }}" method="post">
                    @method('DELETE')
                    @csrf
                    <a href="javascript:void(0);" class="aside-menu__link" id="profile-delete-btn">Удалить профиль</a>
                </form>
            </li>
        </ul>
    </div>
    <div class="aside-content">
        <div class="title-style-six">Для новичков</div>
        <p>Вакансия заполняется по желанию. Размещается бесплатно до 10 дней. Заявки от пользователей вы будете получать на почту. </p>
        <p>Вы можете на время скрыть вашу вакансию, указав Мой статус 'Скрыть из поиска'. </p>
        <p>После оплаты тарифа вам будут доступны контатные данные соискателей.  </p>
    </div>
</div>

resources/views/vacancies/show.blade.php
 @extends('layouts.app')

@section('title') Вакансия - {{ $vacancy->title }} @endsection

@section('main_content')
<div class="section-con section-con__top-pad section-con_mob-pad  section-con_no-cont">
    <div class="container">
        <div class="section-con__row">
            <div class="section-con__main">
                <div class="pages vacancy-mob-pad">
                    <div class="pages__item pages__item_mob bgwhite">
                        <div class="vacancy">
                            <h1 class="title-style-five">{{ $vacancy->title }}</h1>
                            <div class="vacancy__info">{{ $vacancy->position_name }}</div>
                            <div class="el-info vacancy_el_info">
                                <h2 class="title-style-five questionnaire__title">{{ $vacancy->author->name }}</h2>
                                <div class="el-info__item">
                                    <i class="svg-icon">
                                        <svg>
                                            <use xlink:href="{{asset('img/svg/sprite.svg#icon-money')}}"></use>
                                        </svg>
                                    </i>
                                    <!-- t_strong t_red-->
                                    <span class="el-info__text t_strong t_red">{{ $vacancy->salary }} {{$vacancy->price_period_id == "0" ? 'в час' : ' в месяц'}}</span>
                                </div>
                                <div class="el-info__item">
                                    <i class="svg-icon">
                                        <svg>
                                            <use xlink:href="{{asset("img/svg/sprite.svg#label-two")}}"></use>
                                        </svg>
                                    </i>
                                    <span class="el-info__text">{{ $vacancy->country_name }} {{  $vacancy->city_name }}</span>
                                </div>
                                <div class="el-info__item">
                                    <i class="svg-icon">
                                        <svg>
                                            <use xlink:href="{{asset("img/svg/sprite.svg#icon-home")}}"></use>
                                        </svg>
                                    </i>
                                    <span class="el-info__text no-life">{{ $vacancy->document_name }}</span>
                                </div>
                            </div>
                            <div class="el-hr el-mob"></div>
                            <div class="vacancy__item">
                                <ul class="vacancy__list-item vacancy-list">
                                    <li>
                                        <span class="vacancy-list__left">Документы:</span>
                                        <span class="vacancy-list__right">{{ $vacancy->accommodation_names }}</span>
                                    </li>
                                    <li>
                                        <span class="vacancy-list__left">Район города: </span>
                                        <span class="vacancy-list__right">{{ $vacancy->region_name}}</span>
                                    </li>
                                    <li>
                                        <span class="vacancy-list__left">Родной язык: </span>
                                        <span class="vacancy-list__right">{{ $vacancy->language_name}}</span>
                                    </li>
                                    <li>
                                        <span class="vacancy-list__left">Рекомендации:</span>
                                        <span class="vacancy-list__right">{{$vacancy->recommendations == '1' ? "Обязательны рекомендации" : "Не обязательно"}}
                                            </span>
                                    </li>
                                    <li>
                                        <span class="vacancy-list__left">Водительские права:</span>
                                        <span class="vacancy-list__right">{{$vacancy->driver_license == '1' ? "Есть права" : "Нет"}}
                                            </span>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="el-hr"></div>
                        <div class="section-text section-text_mar">
                            <h3>Подробнее о вакансии</h3>
                            <p>{{$vacancy->comments}}</p>
                            @auth
                                <h3>Контакты работодателя</h3>
                                <p>Контакты работодателя Ксения скрыты, для просмотра контактов <a href="{{ route('tariffs') }}">оплатите тариф</a> чтобы связаться
                                    с работодателем на прямую или бесплатно оставьте свой отклик в форме ниже.</p>
                            @endauth
                        </div>
                        <div class="article-info article-info_mar">
                            <div class="article-info__item">
                                <i class="svg-icon">
                                    <svg class="svg-icon_id">
                                        <use xlink:href="{{asset("img/svg/sprite.svg#icon-id")}}"></use>
                                    </svg>
                                </i>
                                <span>{{$vacancy['id']}}</span>
                            </div>
                            <div class="article-info__item">
                                <i class="svg-icon">
                                    <svg class="svg-icon_eye">
                                        <use xlink:href="{{asset("img/svg/sprite.svg#icon-eye")}}"></use>
                                    </svg>
                                </i>
                                <span>{{$vacancy['number_views']}}</span>
                            </div>
                            <div class="article-info__item">
                                <i class="svg-icon">
                                    <svg class="svg-icon_pen">
                                        <use xlink:href="{{asset("img/svg/sprite.svg#icon-pen")}}"></use>
                                    </svg>
                                </i>
                                <span>{{$vacancy->from_date}}</span>
                            </div>
                        </div>
                    </div>
                    <div class="pages__item pages__item_mob response">
                       <h3 class="title-style-four reviews-title">Отклики на вакансию</h3>
                       <div class="response__text"><p>Размещение контактных данных строго запрещено.</p>
                        <p>Анкеты с размещенными контактными данными будут удалены.</p></div>
                        <div class="response__form">
                            <form action="#">
                                <div class="el-form-row">
                                    <span class="text-form-item">Ваш отклик:</span>
                                    <textarea class="type-textarea"></textarea>
                                </div>
                                <div class="form-row-btn form-row-btn_end">
                                    <button class="site-btn bnt-type-one f_15">Отправить отклик</button>
                                </div>
                            </form>
                        </div>
                        <div class="el-hr el-other"></div>
                        <div class="hail">
{{--                            @foreach ($comments as $comment)--}}
{{--                                 <div class="hail__item item-hail">--}}
{{--                                    <div class="item-hail__img">--}}
{{--                                        <img src="img/hail-1.png" alt="img">--}}
{{--                                    </div>--}}
{{--                                <div class="item-hail__content">--}}
{{--                                    <div class="item-hail__top">--}}
{{--                                        <div class="item-hail__name">Анжела, 52</div>--}}
{{--                                        <div class="item-hail__date">15.09.2020</div>--}}
{{--                                    </div>--}}
{{--                                    <div class="item-hail__text">--}}
{{--                                        <p>{{$c->komm}}</p>--}}
{{--                                    </div>--}}
{{--                                </div>--}}
{{--                            </div>--}}
{{--                            @endforeach--}}
                            @foreach($comments as $comment)
                             <div class="hail__item item-hail">
                                <div class="item-hail__img">
                                    <img src="img/hail-2.png" alt="img">
                                </div>
                                <div class="item-hail__content">
                                    <div class="item-hail__top">
                                        <div class="item-hail__name">{{ $comment->author }}, 34</div>
                                        <div class="item-hail__country">Country</div>
                                        <div class="item-hail__date">{{$comment->date_comment}}</div>
                                    </div>
                                    <div class="item-hail__text">
                                        <p>{{$comment->komm}}</p>
                                    </div>
                                </div>
                            </div>
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>

            @include('vacancies.aside')
        </div>
    </div>
</div>

<!-- кнопка прокрутки вверх -->
<div class="scroll-up js-scroll-up">
    <svg class="scroll-up__svg" viewBox="-2 -2 52 52">
        <path class="scroll-up__path js-scroll-up__path" d="M24,0 a24,24 0 0,1 0,48 a24,24 0 0,1 0,-48" />
    </svg>
</div>

<div class="body__opas js-boyd--opas"></div>
@endsection